excerpt_separator: ""
highlighter: rouge
pygments: true
markdown: kramdown
url: https://riahipour.com
title: Ali Riahipour
tagline: Basic life of an iOS developer
description: My awesome new site
paginate: 5
